#! /usr/bin/env bash
set -ex

# This overrides Docker Hub's build command in order to specify the base image
# as build argument. For more information on build hooks and environment
# variables, see: https://docs.docker.com/docker-hub/builds/advanced/

# DOCKER_TAG can be : latest, ubuntu-20.04, v1.0.0, v1.0.0-ubuntu-20.04

if [[ $DOCKER_TAG =~ "^(latest|v[0-9]+\.[0-9]+\.[0-9]+)$" ]]; then
    TAG=debian-buster-slim
else
    # Remove vX.X.X- suffix
    TAG=$(echo $DOCKER_TAG | sed 's/v[0-9]\+.[0-9]\+.[0-9]\+-//')
fi

# Replace first '-' by ':'
# ie, ubuntu-20.04 will be ubuntu:20.04 (image name)
FROM=${TAG/-/:}

docker build . \
    --build-arg FROM=$FROM \
    -f ${DOCKERFILE_PATH:-Dockerfile} \
    -t $IMAGE_NAME
